module.exports = [
  { name: 'ʟᴏᴛᴜꜱ', image: 'lotus.png' },
  { name: 'ꜱᴜɴꜱᴇᴛ', image: 'sunset.png' },
  { name: 'ʙʀᴇᴇᴢᴇ', image: 'breeze.png' },
  { name: 'ᴀꜱᴄᴇɴᴛ', image: 'ascent.png' },
  { name: 'ʙɪɴᴅ', image: 'bind.png' },
  { name: 'ꜱᴘʟɪᴛ', image: 'split.png' },
  { name: 'ɪᴄᴇʙᴏx', image: 'icebox.png' },
  { name: 'ʜᴀᴠᴇɴ', image: 'haven.png' },
  { name: 'ᴘᴇᴀʀʟ', image: 'pearl.png' },
  { name: 'ꜰʀᴀᴄᴛᴜʀᴇ', image: 'fracture.png' },
  { name: 'ᴀʙʏꜱꜱ', image: 'abyss.png' },
  { name: 'ᴄᴏʀʀᴏᴅᴇ', image: 'corrode.png' },
  { name: 'ꜱᴜᴍᴍɪᴛ', image: 'summit.png' },
];