module.exports = [
  { name: 'ʟᴏᴛᴜꜱ', image: 'lotus.webp' },
  { name: 'ꜱᴜɴꜱᴇᴛ', image: 'sunset.webp' },
  { name: 'ʙʀᴇᴇᴢᴇ', image: 'breeze.webp' },
  { name: 'ᴀꜱᴄᴇɴᴛ', image: 'ascent.webp' },
  { name: 'ʙɪɴᴅ', image: 'bind.webp' },
  { name: 'ꜱᴘʟɪᴛ', image: 'split.webp' },
  { name: 'ɪᴄᴇʙᴏx', image: 'icebox.webp' },
  { name: 'ʜᴀᴠᴇɴ', image: 'haven.webp' },
  { name: 'ᴘᴇᴀʀʟ', image: 'pearl.webp' },
  { name: 'ꜰʀᴀᴄᴛᴜʀᴇ', image: 'fracture.webp' },
  { name: 'ᴀʙʏꜱꜱ', image: 'abyss.webp' },
  { name: 'ᴄᴏʀʀᴏᴅᴇ', image: 'corrode.webp' },
  { name: 'ꜱᴜᴍᴍɪᴛ', image: 'summit.webp' },
];